package database

type securityPrivileges int;
const  (
	SecurityAdmin securityPrivileges=iota
	SecuritySelfUserView
	SecuritySelfUserUpdate
	SecuritySelfUserDelete
	SecurityLinkedUsersView
	SecurityLinkedUsersUpdate
	SecurityLinkedUsersDelete
	SecurityAllUsersUpdate
	SecurityAllUsersView
	SecurityAllUsersDelete
	SecurityRolesView
	SecurityRolesUpdate
	SecurityRolesDelete
	SecurityRolesToUserMaintain
	SecuritySelfPaymentsView
	SecurityLinkedUsersPaymentsView
	SecurityAllUsersPaymentsView
)
